apiVersion: v1
kind: Namespace
metadata:
  name: utils
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seashell
  namespace: utils
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seashell
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seashell
subjects:
  - kind: ServiceAccount
    name: seashell
    namespace: utils
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seashell
  namespace: utils
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seashell
  namespace: utils
  labels:
    app: shell
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      tolerations:
        - effect: NoSchedule
          key: node.alpha.kubernetes.io/role
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      serviceAccountName: seashell
      containers:
        - name: seashell
          image: puckpuck/seashell:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBELET
              value: https://$(NODE_NAME):10250
          volumeMounts:
            - name: kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
      volumes:
        - name: kubernetes
          hostPath:
            path: /etc/kubernetes
